### PR TITLE
[chore] Remove reflection usage from KiotaSerialization

### PR DESCRIPTION
**Pull request by andreaTP**
I started picking up #923 again.
Before opening Java to GA I think it makes sense to remove those reflective methods, they look convenient, but I think that a cleaner smaller API is the way to go to start with.

Also, this will prevent accidental usage of reflection on platforms that do not support it completely (like GraalVM native-image).

In case we receive feedback and ask to re-introduce those helpers we can re-evaluate.

### CODE REVIEW

**Review by baywet — CHANGES_REQUESTED** [review]
Thanks for the contribution.
The reflection option was requested by @sebastienlevert in the specification so people don't have to provide the factory method. It's a shorthand for simplicity and since there are overloads accepting the method I don't think it hurts to have those.
They are not used by the generated code.

**Comment by baywet** [comment]
These are most of the arguments I gave to @sebastienlevert + reliability/performance. I'll let you folks discuss that since I'm already in the camp of "we should not be doing any reflection"

**Comment by andreaTP** [comment]
Got it 👍 
Personally, the only "unusual" detail in the reflection-free API is the name of the method IMHO: `createFromDiscriminatorValue` which is rather alien terminology for Java developers.

The resulting API looks cleaner with a more "idiomatic" name like:
```java
KiotaSerialization.deserialize(jsonContentType, strValue, TestEntity::deserializer);
```

**Comment by sebastienlevert** [comment]
In this case @andreaTP if we were to remove the reflection versions of these APIs, would the only thing left on your mind be the `deserializer` vs. `createFromDiscriminatorValue`? That even makes me think that this "wording" might be better in other languages but would impact our GA languages. @baywet any opinions on renaming this factory?

**Comment by andreaTP** [comment]
> if we were to remove the reflection versions of these APIs

I would say that no further actions are required around reflection, all the rest falls in the category of "nice to have".

**Comment by sebastienlevert** [comment]
So current state is OK? Just to make sure I understand correctly?

**Comment by andreaTP** [comment]
Correct, the current status is OK and Kiota is compatible with `native-image` already.

To avoid introducing breaking changes after GA, I warmly encourage you to approve this PR, and we can move on from there.

**Comment by andreaTP** [comment]
Any update? Should I rebase or this is not going to go in?

**Comment by sebastienlevert** [comment]
This should go in. I agree with your concerns and better to avoid reflection in this case.

@baywet make your magic happen 😁

**Comment by baywet** [comment]
Just a heads up on that @sebastienlevert : this means that Java will be different from dotnet. But similar to Go/TS. But I'll proceed. Thanks everyone for the discussion.

**Review by baywet — APPROVED** [review]

**Pull request merged**
