### PR TITLE
feature/devcontainer

### PR DESCRIPTION
**Pull request by baywet**
the dev container is impacted by this https://github.com/microsoft/vscode-dev-containers/issues/1628

### CODE REVIEW

**Comment by ramsessanchez** [comment]
Quick question, I didn't notice a devContainer folder or Dockerfile in our current core/client libraries so I was just hoping you could expand on the purpose of adding it here? Thanks!

**Comment by baywet** [comment]
The idea is to be able to use codespaces, or run from a container locally, instead of having to install java & code on your host OS. You currently only work on Java, kiota, and typewriter (dotnet), so I don't expect that to make a big difference to you. But in my case I'm working in dotnet, java, go, typescript, (ruby, php, python, swift...) and getting tired of updating tooling every other day on my machine 😅

**Comment by baywet** [comment]
as per the vs code files, they are just here to provide a better experience when using vs code, regardless of where vs code is running.

**Comment by ramsessanchez** [comment]
> The idea is to be able to use codespaces, or run from a container locally, instead of having to install java & code on your host OS. You currently only work on Java, kiota, and typewriter (dotnet), so I don't expect that to make a big difference to you. But in my case I'm working in dotnet, java, go, typescript, (ruby, php, python, swift...) and getting tired of updating tooling every other day on my machine 😅

Shoulda stuck to program management. Thanks for the clarification!

**Review by ramsessanchez — APPROVED** [review]

**Pull request merged**
