### PR TITLE
Don't close an InputStream for the user

### PR DESCRIPTION
**Pull request by andreaTP**
It has been much more complicated to correctly Mock the test than the actual fix 😅 .

But here you go, this fixes: #373

### CODE REVIEW

**Review by andrueastman — COMMENTED** [review]
Thanks for the contribution here @andreaTP 

Just a couple of comments
- Any chance you want the changed released, and therefore need to bump the package versions?
- Please check out the CI failure due to the spotBugs before merging.

**Review by baywet — DISMISSED** [review]
Thanks for the contribution. Can you rebase please? And check on the linting issues if any are left

**Comment by andreaTP** [comment]
Oh, sorry if I dropped the ball here.
I'll update the PR and check the linting by the end of the week :+1:

**Comment by andreaTP** [comment]
@andrueastman @baywet , sorry for the super late update, but this PR is nox rebased on the latest `main`, and the SpotBugs issues are solved.

Should be ready for a final review.

**Comment by baywet** [comment]
thanks for fixing those. Would you mind bumping the version and adding a changelog entry as well please?

**Comment by andreaTP** [comment]
done 👍

**Review by baywet — APPROVED** [review]
Thanks for making the changes and for the contribution!

**Pull request merged**
