### PR TITLE
Declare interdependencies as project deps

### PR DESCRIPTION
**Pull request by andreaTP**

### CODE REVIEW

**Review by baywet — APPROVED** [review]
Thanks a lot!
I trust that during publishing gradle will use the package names and versions?

**Comment by andreaTP** [comment]
@baywet Sorry for the noise, I just found that this PR likely broke the publishing mechanism 🙁 
You can reproduce locally with `./gradlew publishToMavenLocal`

**Comment by andreaTP** [comment]
@baywet looks like I got into a rabbit hole here, please revert and let's try to fix everything in another PR.

**Comment by baywet** [comment]
I just fixed it with #140 I believe. Have a look and let me know. We didn't need any of the publications except for one.

**Pull request merged**
